name = "ConjGrad"
uuid = ""
authors = ["Stefano Mandeli <stefano.mandelli@unimi.it>"]
version = "0.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
